import React from 'react';
import { createRoot } from 'react-dom/client';
import { api } from './api';
import './styles.css';
import './enhancements.css';

const demoSummary={total_payments:100,total_at_risk:45000.5,total_recovered:12000,recovery_rate_percent:26.67,open_cases:15,escalated_cases:3};
const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(v)||0);
const pretty=v=>String(v??'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const demoCases=[{id:1,payment_id:'pay_demo_001',status:'OPEN',retry_count:0,diagnosis:'Gateway timeout; customer has prior successful payments.',recommended_action:'SEND_RETRY_LINK',payment:{amount:2499,customer_name:'Arjun Kumar',failure_reason:'Gateway timeout'}},{id:2,payment_id:'pay_demo_014',status:'OPEN',retry_count:0,diagnosis:'Issuer decline; safer to request a fresh payment authorization.',recommended_action:'SEND_RETRY_LINK',payment:{amount:1999,customer_name:'Meera Iyer',failure_reason:'Issuer decline'}},{id:3,payment_id:'pay_demo_021',status:'RECOVERED',retry_count:1,diagnosis:'Transient gateway issue recovered within policy.',recommended_action:'SEND_RETRY_LINK',payment:{amount:4299,customer_name:'Rohit Sharma',failure_reason:'Gateway timeout'}}];
function Badge({status}){const human=String(status||'').toLowerCase()==='needs_human_review'||String(status||'').toLowerCase().replaceAll('_',' ')==='needs human review';return <span className={`status-badge ${human?'needs-human-review':String(status||'').toLowerCase()}`}>{human?'ESCALATED TO HUMAN':pretty(status)}</span>}
function Metric({label,value}){return <div className="metric-card"><div className="metric-label">{label}</div><div className="metric-value">{value}</div></div>}
function App(){
 const[summary,setSummary]=React.useState(demoSummary),[cases,setCases]=React.useState(demoCases),[audit,setAudit]=React.useState([]),[loading,setLoading]=React.useState(false),[live,setLive]=React.useState(false),[failureArmed,setFailureArmed]=React.useState(false),[auditOpen,setAuditOpen]=React.useState(false),[selected,setSelected]=React.useState(null),[batchResult,setBatchResult]=React.useState(null),[notice,setNotice]=React.useState(null),[search,setSearch]=React.useState('');
 const refresh=React.useCallback(async()=>{try{const[s,c,a]=await Promise.all([api.getDashboard(),api.getCases(),api.getAudit()]);setSummary(s);setCases(c.items||[]);setAudit(a.items||[]);setLive(true);return true}catch{setLive(false);return false}},[]);
 React.useEffect(()=>{refresh()},[refresh]);
 const action=async(fn,text,type='success')=>{setLoading(true);setNotice(null);try{const result=await fn();setNotice({type,text:text||result?.message||'Action completed.'});await refresh();return result}catch(e){setNotice({type:'error',text:e.message});}finally{setLoading(false)}};
 const execute=async item=>{setLoading(true);setNotice(null);try{const r=await api.executeRecovery(item.id);setSelected(null);const status=String(r.status||'').toLowerCase();if(status==='needs_human_review'||status.includes('human')||status.includes('escalat')){setFailureArmed(false);setNotice({type:'error',text:'Escalated to Human Review due to gateway failure.'})}else setNotice({type:'success',text:`${pretty(r.action||'Recovery')} completed — ${money(r.amount_recovered)} recovered.`});await refresh()}catch(e){setNotice({type:'error',text:e.message})}finally{setLoading(false)}};
 const seed=()=>action(api.seedDemo,'100 synthetic payments seeded successfully.');
 const reset=async()=>{const r=await action(api.resetDemo,'Demo database reset complete.');if(r){setFailureArmed(false);setBatchResult(null)}};
 const batch=async()=>{setLoading(true);setNotice(null);try{const r=await api.runRecoveryBatch();setBatchResult(r);setNotice({type:'success',text:`Recovered ${money(r.amount_recovered)} across ${r.successful} successful cases.`});await refresh();return r}catch(e){setNotice({type:'error',text:e.message})}finally{setLoading(false)}};
 const arm=async()=>{const r=await action(api.simulateFailure,'Gateway failure detected. Safely escalated to human review.','warning');if(r)setFailureArmed(true)};
 const filtered=cases.filter(c=>`${c.id} ${c.payment_id} ${c.payment?.customer_name||c.customer?.name||''} ${c.status}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="app-shell"><div className="test-banner"><span className="warning-dot">●</span><strong>Razorpay Hackathon Sandbox</strong><span>|</span><strong>Test Mode Active</strong><span>|</span><span>Simulated Gateway</span></div><header className="topbar"><div><div className="eyebrow">Razorpay Hackathon · Track 03</div><h1>RecoverAI <span>— Autonomous Revenue Recovery</span></h1><p className="subtitle">Detect → Diagnose → Decide → Recover → Audit</p></div><div className="top-actions"><span className={`connection-state ${live?'online':'demo'}`}><span/>{live?'Backend connected':'Demo fallback'}</span><button className="ghost-btn" disabled={loading} onClick={seed}>Seed Data</button><button className="ghost-btn" disabled={loading} onClick={reset}>Reset</button></div></header><main>
 {notice&&<div className={`notice ${notice.type}`}><strong>{notice.type==='error'?'Escalation':notice.type==='warning'?'Warning':'Success'}</strong><span>{notice.text}</span><button onClick={()=>setNotice(null)}>×</button></div>}
 <section className="metrics-grid"><Metric label="Total at risk" value={money(summary.total_at_risk)}/><Metric label="Total recovered" value={money(summary.total_recovered)}/><Metric label="Recovery rate" value={`${summary.recovery_rate_percent??0}%`}/><Metric label="Open cases" value={summary.open_cases??0}/><Metric label="Escalated cases" value={summary.escalated_cases??0}/></section>
 <section className="action-center panel"><div><div className="eyebrow">Action center</div><h2>Close the recovery loop</h2><p>Every money action is bounded by the backend policy engine and recorded in the audit trail.</p></div><div className="action-buttons"><button className="primary-btn" disabled={loading||!live} onClick={batch}>{loading?'Processing…':'Run Batch Recovery'}</button><button className={`failure-btn ${failureArmed?'armed':''}`} disabled={loading||failureArmed||!live} onClick={arm}>{failureArmed?'⚠ Failure Armed — Next Execute Will Escalate':'⚠ Arm Failure Simulation'}</button><button className="audit-btn" onClick={()=>setAuditOpen(true)}>View Compliance Audit</button></div></section>
 <section className="panel cases-panel"><div className="panel-header"><div><div className="eyebrow">Recovery queue</div><h2>Payment recovery cases</h2><p>{live?`${cases.length} cases loaded from backend`:'Backend unavailable — showing demo fallback'}</p></div><div className="panel-tools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search cases…" aria-label="Search cases"/><span className="test-chip">RAZORPAY TEST MODE</span></div></div><div className="table-wrap"><table><thead><tr><th>Case</th><th>Customer</th><th>Payment</th><th>Amount</th><th>Diagnosis</th><th>AI Action</th><th>Status</th><th/></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>#{item.id}</strong></td><td>{item.customer?.name||item.payment?.customer_name||'Customer'}</td><td className="muted">{item.payment_id}</td><td className="amount">{money(item.amount??item.payment?.amount)}</td><td className="diagnosis">{item.diagnosis||item.payment?.failure_reason||'Payment failure detected'}</td><td>{pretty(item.recommended_action)}</td><td><Badge status={item.status}/></td><td>{String(item.status).toUpperCase()==='OPEN'&&live?<button className="execute-btn" disabled={loading} onClick={()=>execute(item)}>Execute</button>:<button className="details-btn" onClick={()=>setSelected(item)}>Details</button>}</td></tr>)}</tbody></table>{filtered.length===0&&<div className="empty-state">No recovery cases match your search.</div>}</div></section>
 <section className="pitch-proof"><div><strong>AI recommendation</strong><span>LLM proposes the action.</span></div><b>→</b><div><strong>Policy engine</strong><span>Backend gates the action.</span></div><b>→</b><div><strong>Razorpay Test Mode</strong><span>Bounded execution.</span></div><b>→</b><div><strong>Audit trail</strong><span>Every decision is explainable.</span></div></section>
 </main>
 {batchResult&&<div className="modal-backdrop" onMouseDown={()=>setBatchResult(null)}><div className="case-modal batch-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><div className="eyebrow">Batch recovery result</div><h2>Revenue recovery completed</h2></div><button className="close-btn" onClick={()=>setBatchResult(null)}>×</button></div><div className="batch-grid"><div><span>Cases</span><strong>{batchResult.total_cases}</strong></div><div><span>Attempted</span><strong>{batchResult.attempted}</strong></div><div><span>Successful</span><strong className="positive">{batchResult.successful}</strong></div><div><span>Failed</span><strong className="negative">{batchResult.failed}</strong></div><div><span>Escalated</span><strong className="negative">{batchResult.escalated}</strong></div><div><span>Amount at risk</span><strong>{money(batchResult.amount_at_risk)}</strong></div><div><span>Amount recovered</span><strong className="positive">{money(batchResult.amount_recovered)}</strong></div><div><span>Recovery rate</span><strong>{batchResult.recovery_rate}%</strong></div></div><p className="modal-footnote">Backend batch metrics · Razorpay Test Mode · bounded recovery workflow.</p></div></div>}
 {selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><div className="case-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><div className="eyebrow">Recovery case #{selected.id}</div><h2>{selected.payment?.customer_name||selected.customer?.name}</h2></div><button className="close-btn" onClick={()=>setSelected(null)}>×</button></div><div className="case-detail"><div><span>Amount</span><strong>{money(selected.amount??selected.payment?.amount)}</strong></div><div><span>Status</span><Badge status={selected.status}/></div><div><span>Retry count</span><strong>{selected.retry_count}</strong></div></div><h3>Diagnosis</h3><p>{selected.diagnosis||'Payment failure requires recovery review.'}</p><h3>Recommended action</h3><p>{pretty(selected.recommended_action)}</p></div></div>}
 {auditOpen&&<div className="drawer-backdrop" onMouseDown={()=>setAuditOpen(false)}><aside className="audit-drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-header"><div><div className="eyebrow">Compliance proof</div><h2>Audit Trail</h2></div><button className="close-btn" onClick={()=>setAuditOpen(false)}>×</button></div><p>Compliance events from the backend, including diagnosis, policy gating and execution.</p><div className="json-list">{audit.length?audit.map(event=><pre key={event.id}>{JSON.stringify(event,null,2)}</pre>):<div className="empty-state">No audit events yet. Seed and execute a case to populate live compliance events.</div>}</div></aside></div>}
 </div>}
createRoot(document.getElementById('root')).render(<App/>);
